### ISSUE TITLE
Add project: IP2Trace Python

### ISSUE THREAD

**Issue by ip2location-com** [lukasmasuch/best-of-python#17]
**Project details:**

- Project Name: IP2Trace Python
- Github URL: https://github.com/ip2location/ip2trace-python
- Category:  Others
- License: MIT
- Package Managers: pypi:IP2Trace

**Additional context:**

IP2Trace Python is a ready-to-use Python tool allowing users to display the geolocation information, such as country, region, city, latitude, longitude, zip code, time zone, ISP, domain name, connection type, area code, weather, mobile network, elevation, usage type in the IP traceroute results. It supports both IPv4 and IPv6 traceroute.

**Comment by lukasmasuch** [comment]
@ip2location Thanks for the contribution. I added it to one of our other lists [here](https://github.com/ml-tooling/best-of-web-python/commit/053cac56da970a609a5eb631cd78a45b4c27d692).
