### ISSUE TITLE
Add project: ubelt

### ISSUE THREAD

**Issue by Erotemic** [lukasmasuch/best-of-python#5]
**Project details:**
Ubelt is a small library of robust, tested, documented, and simple functions that extend the Python standard library. It has a flat API that all behaves similarly on Windows, Mac, and Linux (up to some small unavoidable differences). Almost every function in ubelt was written with a doctest. This provides helpful documentation and example usage as well as helping achieve 100% test coverage (with minor exceptions for Python2, Windows, etc...).

- Project Name: ubelt
- Github URL: https://github.com/Erotemic/ubelt
- Category:  utilities
- License: Apache License 2.0
- Package Managers:  pypi:ubelt

**Comment by lukasmasuch** [comment]
@Erotemic Thanks for the suggestion! I added it to the list https://github.com/ml-tooling/best-of-python/commit/b29b05f36610701d0378f1c2e2da1b4a1f7c345d
