### ISSUE TITLE
Add project: Mozart - An optical music recognition (OMR) system

### ISSUE THREAD

**Issue by aashrafh** [lukasmasuch/best-of-python#9]
**Project details:**

- Project Name: Mozart
- Github URL: https://github.com/aashrafh/Mozart
- Category:  Computer & Machine Vision
- License: Apache-2.0
- Package Managers: None

**Additional context:**

The aim of this project is to develop a sheet music reader. This is called Optical Music Recognition (OMR). Its objective is to convert sheet music to a machine-readable version. We take a simplified version where we convert an image of sheet music to a textual representation that can be further processed to produce midi files or audio files like wav or mp3.

**Comment by lukasmasuch** [comment]
@aashrafh Thanks for your suggestion! I added it to our machine-learning / data-engineering list here: https://github.com/ml-tooling/best-of-ml-python/commit/8bc642964df9ed27e89732aeaceb7107b7e9caaa
